### ISSUE TITLE
[Feature] plugin system

### ISSUE THREAD

**Issue by ui3o** [yazgoo/umberwm#13]
Hi!

I have an idea, and I would like to join to this development. I like this core functionality.

What do you think about this? 
- The main function is developed like you did. Build a main program which can read the config directory from the user home folder
- All the config file built as compiled Rust lib (plugin). The plugin system from here: https://github.com/luojia65/plugin-system-example
- The main program read the plugins and execute them. There are name convention like: 01_layout_exmaple.lib (order_type_anyExtraName)
- When change the layout as normal, only activate the next plugin 
- Also possible to define key listener plugin, if needed. Like: 01_key_example.lib (order_type_anyExtraName)
- There have to be 1 core layout, and 1 core key listener if no plugin available. 
- If the one plugin will be updated, the OS detect the file changes and the main program reload the plugin, and if new plugin will be available the  main program add to the layout list or to key listener list. The process also same for the deletion, if one plugin will be deleted the main program remove from the plugin list.
- If no plugin available the core plugins going to be available only

In this case you do not need to restart the main program if something need to be change. The other main feature is fast, because all plugin call are native. Only need to create some injection point for the plugins. 

What do you think about this idea? Would you like to add this core feature to your core lib?

Thank you for this tinywm!

**Comment by yazgoo** [comment]
Hi, thanks for your issue.

If I understand correctly, you're trying to achieve hot reloading configuration, but keep it as code (which I think is fun idea :) ).

- The key plugin would contain `custom_actions` and `wm_actions` ?
- The layout plugin would contain the rest ?

Can't all this be done in a custom "main" requiring this crate ?

If so, I think that would be nice indeed, but I'd like to leave it out of this project (to leave it as simple as possible), and I guess this could be do-able.

We could do another repo for that (from the beginning I've wanted do a more "user friendly" version of this, maybe this could be part of that).

**Comment by ui3o** [comment]
Hi, 

Yes you are right, this is a hot reloaded concept. 

- _The key plugin would contain custom_actions and wm_actions ?_ **Yes**
- _The layout plugin would contain the rest ?_ **Yes**
- _Can't all this be done in a custom "main" requiring this crate ?_  **I was thinking about this... Actually if they are separated, possible to point to the layout from the custom action. Like activate  01_layout.lib**
- **We could do another repo for that.** **Sure! Lets do that. Would you like me to join as a developer?**

Thanks
