### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by mfdorst** [yazgoo/umberwm#27]
We're getting
```
Error: fatal: unable to access 'https://github.com/yazgoo/umberwm/': The requested URL returned error: 500
```
I have no idea why that would happen. I tried re-running the jobs and they failed again with the same error. It was working just a few hours ago, not sure what changed.

**Comment by yazgoo** [comment]
Looks like a transient error on github side
https://www.githubstatus.com/ doesn't reflect it though

**Comment by mfdorst** [comment]
Seems to have fixed itself.
